# you need a steam account to extract the games from the account
# URL: https://steamcommunity.com/id/ACCOUNT_NAME/games/?tab=all
# use the inspect element tool to get the HTML code of the page
# paste in temp/steam_games.html

# JavaScript code to scroll the page to the bottom, paste it in the console for the page to load all date
"""
let scrollInterval = setInterval(() => {
    window.scrollBy(0, 1000); // Scrolls down by 1000px
    if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
        clearInterval(scrollInterval); // Stops the scroll once you reach the bottom
    }
}, 50);
"""


import os
import csv
from bs4 import BeautifulSoup
from rich.console import Console
from rich.table import Table


def get_playtime_class(_soup):
    total_played_element = _soup.find(string="TOTAL PLAYED")
    if total_played_element:
        parent_span = total_played_element.find_parent('span').find_parent('span')
        if parent_span and 'class' in parent_span.attrs:
            return parent_span['class'][0]

    return None


def get_playtime_from_tag(_tag):
    _playtime = 0
    if playtime_tag:
        playtime_modified = playtime_tag.text.strip().replace('TOTAL PLAYED', '')
        playtime_modified = playtime_modified.replace(',', '.').strip()

        _playtime = float(''.join(filter(lambda x: x.isdigit() or x == '.', playtime_modified)))

        if 'minutes' in playtime_modified:
            _playtime /= 60

    return _playtime


html_file_path = 'temp/steam_games.html'
if not os.path.exists(html_file_path):
    print(f"File not found: {html_file_path}")
    exit(1)

with open(html_file_path, 'r', encoding='utf-8') as file:
    html_content = file.read()

soup = BeautifulSoup(html_content, 'html.parser')

playtime_class = get_playtime_class(soup)

games = []
unplayed_count = 0
total_playtime = 0

# you probably have to modify/adjust these classes to your needs/they seem autogenerated
for game_div in soup.find_all('div', class_='_2-pQFn1G7dZ7667rrakcU3'):
    title_tag = game_div.find('a', class_='_22awlPiAoaZjQMqxJhp-KP')
    playtime_tag = game_div.find('span', class_=playtime_class)

    if title_tag:
        title = title_tag.text.strip()
        playtime = get_playtime_from_tag(playtime_tag)
        total_playtime += playtime

        if playtime == 0:
            unplayed_count += 1

        games.append((title, playtime))


# Create a table using rich
table = Table(title="Steam Games and Playtime")

table.add_column("Game Title", justify="left", no_wrap=True)
table.add_column("Playtime (h)", justify="left", no_wrap=True)

for game in games:
    table.add_row(game[0], f"{game[1]:.2f}")

# Print the table
console = Console()
console.print(table)

# Print the summary
total_games = len(games)
console.print("")
console.print(f"Total games: {total_games}")
console.print(f"Unplayed games: {unplayed_count}")
console.print(f"Total Playtime: {total_playtime:.2f} hours")

# Save the data to a CSV file
output_csv_path = 'output/steam_games.csv'
os.makedirs(os.path.dirname(output_csv_path), exist_ok=True)

with open(output_csv_path, 'w', newline='', encoding='utf-8') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(['Game Title', 'Playtime (h)'])
    csvwriter.writerows(games)

console.print(f"Data saved to {output_csv_path}")
